### ISSUE TITLE
Error on Portfolio: Number fields shows NaN

### ISSUE THREAD

**Issue by IngarMa** [Puzzlepart/prosjektportalen#582] opened 2018-07-13 05:36 UTC
#### Category
[X ] Bug

[X] Question

#### Environment

[ X] SharePoint Online

#### Browser

[X] Chrome
[X] Edge
#### Summary

Trying to make a new view, with economic numbers (existing)
Keep on getting Kr NaN as result, not actual number from project.

![image](https://user-images.githubusercontent.com/32195694/42674234-1ef4f292-866f-11e8-8dd3-77cb1c251257.png)

#### Version

2.1.78.

#### Expected / Desired Behavior / Question

See the numbers from project :-)

#### Observed Behavior

Kr. Nan instead of sums, on projectstatus page

#### Steps to Reproduce

Created a new view, with the thought of having an economic overview of the projects

**Comment by olemp** [comment] 2018-07-13 09:17
@IngarMa Looks like this is related to SharePoint, and not prosjektportalen. I can reproduce this in several environments, and the code for the portfolio has not changed the last few months.

I can reproduce the same in Search Query Tool (https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool)

![image](https://user-images.githubusercontent.com/7606007/42683683-56162e98-868e-11e8-9700-99c347f806a9.png)

**Comment by olemp** [comment] 2018-07-13 10:09
@IngarMa I'm guessing you mean Portfolio.aspx, not ProjectStatus.aspx?

**Comment by IngarMa** [comment] 2018-07-13 10:12
@olemp Yes, that's correct

**Comment by olemp** [comment] 2018-07-13 10:17
When did the issue start appearing @IngarMa? Has it been working on 2.1.78 previously?

**Comment by IngarMa** [comment] 2018-07-13 10:22
Tried creating a new view, with more economic posts in it for the first time really. So haven't seen it working before either, no.

**Comment by olemp** [comment] 2018-07-13 12:02
Most likely related to issues with the SP search service. Will reopen if signs shows otherwise.

**Comment by tarjeieo** [comment] 2018-08-27 10:31
Seeing this at other customers now. Will have another look.

**Comment by olemp** [comment] 2018-08-29 13:02
Having the same issue in my dev tenant. Looks to be search related.

**Comment by IngarMa** [comment] 2018-09-24 08:02
Any development on this?

**Comment by olemp** [comment] 2018-09-24 08:07
@IngarMa This shouldn't be an issue in the latest version.

**Comment by tarjeieo** [comment] 2018-10-01 19:04
Verified fixed for one more customer. Closing. Nice job @olemp !

**Closed by tarjeieo** 2018-10-01 19:04 UTC
