### ISSUE TITLE
Installation fails: Exception = Unable to find the specified file (File ICO-Site-Global-13.png not found in directory)

### ISSUE THREAD

**Issue by stalsberg** [Puzzlepart/prosjektportalen#649] opened 2019-03-04 12:12 UTC
#### Environment

[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ ] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[X] Other

#### Version

Please specify what version you are using: [ 2.4.0.e96c5831]

#### Summary

Installation always fail with the error: "Object reference not set to an instance of an object" when the installer is supposed to run  Apply-PnPProvisioningTemplate.

The install log file logs the following:
powershell.exe Error: 0 : 2019-03-04 12.54.47.6041      [OfficeDevPnP.Core]     [0]     [Error] File ICO-Site-Global-13.png not found in directory /sites/Prosjektportalen/siteassets/pp/img. Exception = Unable to find the specified file.    0ms
powershell.exe Error: 0 : 2019-03-04 12.54.47.6041      [OfficeDevPnP.Core]     [0]     [Error] File ICO-Site-Global-13.png not found in directory /sites/Prosjektportalen/siteassets/pp/img. Exception = Unable to find the specified file.    0ms

SharePointPnPPowerShellOnline module is version 3.6.1902.2

#### Expected / Desired Behavior / Question

I expect the file ICO-Site-Global-13.png to be found in the /sites/Prosjektportalen/siteassets/pp/img directory, but it isn't there.

#### Observed Behavior

Installation fails because some site assests are missing.

#### Steps to Reproduce

Do a clean install.

**Comment by olemp** [comment] 2019-03-04 13:26
Hi @stalsberg,

We've had several install with PnP version 3.6.1902.2 ourselves, and we've had no reports from users installing v2.4.0 with this PnP version.

Have you read through the installation documentation? https://github.com/Puzzlepart/prosjektportalen/wiki/Installation

**Comment by tarjeieo** [comment] 2019-03-19 12:51
Looks like this is the same issue as #654. Have a go at the latest release: https://github.com/Puzzlepart/prosjektportalen/releases/tag/v2.4.1

**Comment by tarjeieo** [comment] 2019-03-22 11:16
Feel free to shoot me an email at tarjeieo@puzzlepart.com if you want to troubleshoot this using Teamviewer, Skype.

**Comment by tarjeieo** [comment] 2019-03-26 08:40
Closing as duplicate of #654

**Closed by tarjeieo** 2019-03-26 08:40 UTC
Labels: bug, duplicate, installation
