### ISSUE TITLE
Broken link "Siste informasjonslementer" {SiteUrl}/Lists/Informasjon/AllItems.asp

### ISSUE THREAD

**Issue by pettersh** [Puzzlepart/prosjektportalen#203] opened 2017-06-22 12:27 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

I've installed prosjektportalen in a customer tenant.
On the page "Møtereferat" (SitePages/Mom.aspx) there is a "**Siste informasjonselementer**" webpart.
When clicking on the webpart title I'm directed to **{SiteUrl}/Lists/Informasjon/AllItems.asp** which doesn't exist.

The Url should go to **{SiteUrl}/Lists/Informasjon**  or **{SiteUrl}/Lists/Informasjon/AllItems.aspx** instead.

It can be reproduced in **https://pzlcloud.sharepoint.com/sites/ppdemo_v2/digitale-oslo-2020/SitePages/Mom.aspx** 

#### Version

Please specify what version you are using: [v.1.13.4]

You can find the version you are using in the bottom left corner of any page in the Project portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
_If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!_

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

**Comment by pettersh** [comment] 2017-06-22 12:30
If I edit the webpart, expand the Advanced section I can see that the Title URL is wrong

**Comment by olemp** [comment] 2017-06-22 12:37
If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.

Have you tried with latest? 👍🏻

**Comment by olemp** [comment] 2017-06-22 13:36
Thanks for reporting this. This was fixed in the latest release 1.15.8.

https://github.com/Puzzlepart/prosjektportalen/releases/tag/v1.15.8

**Closed by olemp** 2017-06-22 13:36 UTC
