### ISSUE TITLE
Phase info on Projects on Portfolio mismatching after upgrade

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#467] opened 2017-12-14 09:04 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Environment

[X ] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[ X] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Summary

After upgrade of our installation we reordered our Phases in Termstore.
Project level seems OK but Portfolio level seems to keep the "Old" phase values still

#### Version

Please specify what version you are using: [ 2.1.20]

#### Expected / Desired Behavior / Question
We assumed that Phase name on Portfolio level should match Project Level.

#### Observed Behavior
Phase info on Portfolio differs from Project level

#### Steps to Reproduce
![image](https://user-images.githubusercontent.com/33092566/33983915-1cdb541a-e0b6-11e7-8d6f-ae1d75cad72b.png)
![image](https://user-images.githubusercontent.com/33092566/33983934-2b2249c0-e0b6-11e7-8013-708f4b5bcd45.png)

**Comment by tarjeieo** [comment] 2017-12-18 12:45
Hi @jahali,

I believe this is just caused by the search service lagging a little behind. Do you still have the problem today?

If you do, try the following
1. Go to site settings for the top level, go to "Manage search and offline availability" (from memory, might be slighlty different).
2. Click re-index site.
3. OK, ok. Wait an hour or so. Should have been updated.

-Tarjei

**Comment by jahali** [comment] 2017-12-19 09:55
Hi,
Still the same after re-index of the site

Jan

**Comment by tarjeieo** [comment] 2018-01-31 14:25
Is this still an issue @jahali ? SharePoint should have had enough time to reindex now ;)

**Comment by jahali** [comment] 2018-01-31 18:23
Hi,


Still the same with phase status on portfolio level




Best regards,
Jan Lindset
Head of IT Applications
_______________________________________________
Goodtech AS
Visiting address: Innspurten 15 0663 Oslo
Postal address: P.O. Box 6578 Etterstad, NO-0607 Oslo
Phone: +47 926 06 428
E-mail: jan.lindset@goodtech.no<mailto:jan.lindset@goodtech.no>
www.goodtech.no<http://www.goodtech.no>

[https://i.xink.io/Images/Get/L341/i]

the preferred choice for industrial efficiency



________________________________

**Comment by jahali** [comment] 2018-02-14 09:46
Hi,
I have found another place where the same issue occurs.
In my risk item, the identified "phase" differs when in view mode  vs  edit mode
And it is the exact same differences as in Portfolio view


![image](https://user-images.githubusercontent.com/33092566/36197475-1b6e9d78-1174-11e8-8d30-e15b23c9cfb0.png)
![image](https://user-images.githubusercontent.com/33092566/36197486-24b07172-1174-11e8-9604-91892e245881.png)

**Comment by tarjeieo** [comment] 2018-02-14 11:53
Looks like the issue is the following
- https://social.technet.microsoft.com/Forums/ie/en-US/3f320380-c357-4e59-a623-ee49dcd9eed8/taxonomy-term-update-in-sharepoint-onilne?forum=onlineservicessharepoint
- https://social.msdn.microsoft.com/Forums/sqlserver/en-US/c27c3ae9-b67d-45f9-90ec-19536a6d909d/o365-sharepoint-taxonomy-update-scheduler-not-updating?forum=sharepointdevelopment

For some reason the taxonomy sync is not working in your site collection. 

Let me know if I should follow this up in your environment or if you'll handle this yourself.

**Comment by tarjeieo** [comment] 2018-02-14 12:16
Contact me by e-mail if this is something I should look into for you. Closing this as the issue is not really Project portal related.

**Closed by tarjeieo** 2018-02-14 12:16 UTC
