### ISSUE TITLE
Project creation failing on copying documents when installing to root site collection 

### ISSUE THREAD

**Issue by IngarMa** [Puzzlepart/prosjektportalen#436] opened 2017-11-10 08:25 UTC
#### Category
[X ] Bug

#### Environment
[ X] SharePoint 2013
#### Summary

Please summarize the issue.

#### Version

Please specify what version you are using: [2.1..13 ]

#### Expected / Desired Behavior / Question
Want to create a project room, fails when posting to logg list.
This is a new bug created, after issue #422 was closed.

#### Observed Behavior
fails when posting to logg list.

![image](https://user-images.githubusercontent.com/32195694/32649099-13b5430a-c5f9-11e7-9757-e2974f4e99b8.png)

Here are the columns on the log-list, anything missing?
![image](https://user-images.githubusercontent.com/32195694/32649122-2b995f1a-c5f9-11e7-91b4-438573daa360.png)

#### Steps to Reproduce
Trying to create a room, in sp2013

**Comment by olemp** [comment] 2017-11-22 12:49
Any updates on this @IngarMa?

**Comment by IngarMa** [comment] 2017-11-22 13:07
@olemp  Give me until tomorrow, and i'll give you an update :-)

**Comment by IngarMa** [comment] 2017-11-23 09:47
got this: 
![image](https://user-images.githubusercontent.com/32195694/33166641-3e3ac8ce-d03b-11e7-9ead-a0d6adaef0d3.png)

![image](https://user-images.githubusercontent.com/32195694/33166671-6306e4e4-d03b-11e7-87fa-b7531e5de743.png)
![image](https://user-images.githubusercontent.com/32195694/33166681-70cdfc52-d03b-11e7-9538-5348ffc88c7d.png)

![image](https://user-images.githubusercontent.com/32195694/33166710-7f0917d4-d03b-11e7-8484-bd3684c11696.png)


Also found this when googling: https://sharepoint.stackexchange.com/questions/208803/the-property-description-does-not-exist-on-type

I've not encountered this in my o365 environment, only in the current sp2013 environment.
Anything you could look in to?

**Comment by tarjeieo** [comment] 2017-11-23 09:50
Think we need to look into this thoroughly in your environment. Shoot me an e-mail at tarjeieo @ puzzlepart.com and we can discuss how we solve this.

**Comment by tarjeieo** [comment] 2017-11-29 12:26
Closing until we can reproduce, ref. e-mail.

**Comment by tarjeieo** [comment] 2017-12-06 14:04
Was able to reproduce this now in SharePoint 2016 on the root site collection only. @IngarMa, have you also installed the solution on the root site collection?

I was able to workaround the issue by going to Site Settings -> Prosjektportalen - Listeinnhold -> Delete all the items. After that new projects are being created. Can you try this?

**Comment by IngarMa** [comment] 2017-12-07 08:11
@tarjeieo  can confirm that this worked - just tested and created successfully here now

**Comment by tarjeieo** [comment] 2017-12-07 08:24
Ah, that's great, then the problem is identified! Will let you know here once this is fixed!

**Comment by tarjeieo** [comment] 2017-12-20 10:59
Hi again,

We believe this is fixed now in the last release (2.1.22). Can you try again?

-Tarjei

**Closed by tarjeieo** 2017-12-20 10:59 UTC
Labels: bug

**Comment by IngarMa** [comment] 2018-01-02 09:33
@tarjeieo works as intended wit 2.1.22, thanks!
