### ISSUE TITLE
Project metadata fields linked to document library not accessible from Word documents

### ISSUE THREAD

**Issue by jahali** [Puzzlepart/prosjektportalen#425] opened 2017-10-25 13:02 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[ X] Bug

[ ] Question

#### Environment

[ X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Summary

Project Metadata like "Project name in the financial system" that are "synchronized" with the Document Library is not working properly.
Since the columns are hidden in the Document Library it is not possible for the Documents to connect to these fields.
To investigate this we need to have the columns or notHidden.
If this only is necessary the first time to make the connection in the documents and that they later one once again can be Hidden is uncertain.

#### Version

Please specify what version you are using: [v2.1.13.ea1c1958 ]

#### Expected / Desired Behavior / Question
Need to be able to connect to these fields from the Word documents in the Library

#### Observed Behavior
Fields not visible in Word, and they can therefore not be connected.

#### Steps to Reproduce
Open a word document and look at the choices from the menu:
Insert\Quick Parts\Document property

**Comment by olemp** [comment] 2017-10-25 13:08
Hello @jahali,

The fields are hidden for the content type _Prosjektdokument_ since these are synced from the project itself, and we don't want the users to edit them manually.

If you have some familiarity with SharePoint administration, you can make the fields visible again in the site collection where you've installed Prosjektportalen.

The content type can be found here: {sitecollection}/_layouts/15/ManageContentType.aspx?ctype=0x010100293FDE3FCADA480B9A77BBDAD7DFA28C01&Source=https%3A%2F%2Folemp%2Esharepoint%2Ecom%2Fsites%2Fpp-program-04%2F_layouts%2F15%2Fmngctype%2Easpx

.. where `{sitecollection}` is the root URL of your site collection.

**Comment by jahali** [comment] 2017-10-26 07:27
OK, so the fields are made visible.
And after creating a new project, add relevant project data I go to the Doc library to upload a document.

The fields are filled with default data as specified in the project. 
**Except** for "Service Area". This field is loaded with the term "Work and business", a term that is disabled in the termstore, and therefore not selected in the project.

The same seems to be the issue with the field "Phase", that is loaded with the term "Plan".
Both of these have their values written in red...

**Comment by olemp** [comment] 2017-10-26 07:32
@jahali Not quite sure what you mean. Can you add some screenshots to describe the issue you're experiencing?

**Comment by jahali** [comment] 2017-10-26 07:34
![image](https://user-images.githubusercontent.com/33092566/32040377-e0c1f02a-ba30-11e7-9a14-515d830b10d3.png)

**Comment by olemp** [comment] 2017-10-26 07:35
Thanks! ... and you did not select `Work and business` for Service Area and `Plan` for Phase in the project properties?

**Comment by jahali** [comment] 2017-10-26 07:36
The Service area as displayed in red is not selected on the project.
It is even set at "not selectable" in Termstore

**Comment by jahali** [comment] 2017-10-26 07:36
The same goes for the Phase

**Comment by olemp** [comment] 2017-10-26 07:37
This is very strange @jahali. Is this Office 365 or on-prem?

**Comment by jahali** [comment] 2017-10-26 07:37
office 365

**Comment by olemp** [comment] 2017-10-26 07:37
Are you able to give me access? 

olemp@puzzlepart.com

**Comment by jahali** [comment] 2017-10-26 07:41
Skype perhaps?

**Comment by olemp** [comment] 2017-10-26 07:58
This was caused by metadata on the document itself. Closing. J

**Closed by olemp** 2017-10-26 07:58 UTC
